version: '3.1'

services:
  shippyclient:
    build: ./shippyclient 
    environment: 
      MICRO_REGISTRY: "mdns"
  
  userclient:
    build: ./userclient 
    environment: 
      MICRO_REGISTRY: "mdns"    

  shippyserver:
    build: ./shippyserver
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  shippyvessel:
      build: ./shippyvessel 
      ports :
        - 50052:50051
      environment: 
        MICRO_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"
        DB_HOST: "datastore:27017"
    
  userserver:
    build: ./userserver
    ports:
      - 50053:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "database" 
    depends_on: 
      - database

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

