// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Likes                int32    `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes             int32    `protobuf:"varint,2,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Post) GetDislikes() int32 {
	if m != nil {
		return m.Dislikes
	}
	return 0
}

type Bloger struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Post                 *Post    `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bloger) Reset()         { *m = Bloger{} }
func (m *Bloger) String() string { return proto.CompactTextString(m) }
func (*Bloger) ProtoMessage()    {}
func (*Bloger) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Bloger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bloger.Unmarshal(m, b)
}
func (m *Bloger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bloger.Marshal(b, m, deterministic)
}
func (m *Bloger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bloger.Merge(m, src)
}
func (m *Bloger) XXX_Size() int {
	return xxx_messageInfo_Bloger.Size(m)
}
func (m *Bloger) XXX_DiscardUnknown() {
	xxx_messageInfo_Bloger.DiscardUnknown(m)
}

var xxx_messageInfo_Bloger proto.InternalMessageInfo

func (m *Bloger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bloger) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Bloger) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "main.Post")
	proto.RegisterType((*Bloger)(nil), "main.Bloger")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2,
	0xe0, 0x62, 0x09, 0xc8, 0x2f, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xc9, 0xcc, 0x4e, 0x2d, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x84, 0xa4, 0xb8, 0x38, 0x52, 0x32, 0x8b, 0x21,
	0x12, 0x4c, 0x60, 0x09, 0x38, 0x5f, 0x29, 0x82, 0x8b, 0xcd, 0x29, 0x27, 0x3f, 0x3d, 0xb5, 0x48,
	0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x15, 0xac, 0x95, 0x33, 0x08, 0xcc, 0x06, 0xe9, 0xcc,
	0x49, 0x2c, 0x2e, 0x01, 0x8b, 0x33, 0x81, 0xc5, 0xe1, 0x7c, 0x21, 0x39, 0x2e, 0x96, 0x82, 0xfc,
	0xe2, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x2e, 0x3d, 0x90, 0x43, 0xf4, 0x40, 0xae,
	0x08, 0x02, 0x8b, 0x27, 0xb1, 0x81, 0x1d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x29,
	0x74, 0x1a, 0xb0, 0x00, 0x00, 0x00,
}
